
## Buttons
set_property -dict {PACKAGE_PIN AV39} [get_ports rst_i]
set_property IOSTANDARD LVCMOS18 [get_ports rst_i]

set_property -dict {PACKAGE_PIN AP40} [get_ports start_i]
set_property IOSTANDARD LVCMOS18 [get_ports start_i]

## Switches
set_property PACKAGE_PIN BB31 [get_ports sw7_i]
set_property IOSTANDARD LVCMOS18 [get_ports sw7_i]

## LEDs
set_property PACKAGE_PIN AM39 [get_ports led0_o]
set_property IOSTANDARD LVCMOS18 [get_ports led0_o]
set_property SLEW SLOW [get_ports led0_o]
set_property DRIVE 4 [get_ports led0_o]

## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]



set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[3]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[4]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[7]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[10]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[16]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[17]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[5]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[14]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[18]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[2]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[9]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[12]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[13]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[19]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[20]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[1]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[6]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[8]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[11]}]
set_property MARK_DEBUG true [get_nets {FIL_four_to_one_mux_selects[15]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[8]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[10]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[17]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[20]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[24]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[29]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[31]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[12]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[4]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[0]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[1]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[14]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[15]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[18]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[25]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[28]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[27]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[5]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[9]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[13]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[16]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[19]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[21]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[30]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[2]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[3]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[6]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[7]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[11]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[22]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[23]}]
set_property MARK_DEBUG true [get_nets {neorv32_run_counter[26]}]
set_property MARK_DEBUG true [get_nets {S_top_Current_State[0]}]
set_property MARK_DEBUG true [get_nets {S_top_Current_State[1]}]
set_property MARK_DEBUG true [get_nets {S_top_Current_State[2]}]
set_property MARK_DEBUG true [get_nets {S_top_Current_State[3]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[10]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[3]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[7]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[1]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[5]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[8]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[11]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[2]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[9]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[12]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[14]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[5]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[9]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[11]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[7]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[15]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[0]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[3]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[6]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[8]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[15]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[2]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[1]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[4]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[3]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[6]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[12]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[10]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[13]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[10]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[4]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[15]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[0]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[12]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[2]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[0]}]
set_property MARK_DEBUG true [get_nets {total_classes_counter[8]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[4]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[11]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[14]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[6]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[9]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[13]}]
set_property MARK_DEBUG true [get_nets {total_label_0_classes_counter[14]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[1]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[5]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[13]}]
set_property MARK_DEBUG true [get_nets {total_label_1_classes_counter[7]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[4]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[5]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[9]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[16]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[25]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[27]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[31]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[7]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[1]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[6]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[12]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[14]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[15]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[18]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[21]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[26]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[29]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[3]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[10]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[11]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[19]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[22]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[23]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[28]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[30]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[0]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[2]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[8]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[13]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[17]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[20]}]
set_property MARK_DEBUG false [get_nets {PC_data_out[24]}]
set_property MARK_DEBUG true [get_nets bit_fault_inj_en]
set_property MARK_DEBUG true [get_nets fault_injection_en]
set_property MARK_DEBUG true [get_nets fifo_empty]
set_property MARK_DEBUG true [get_nets fifo_error]
set_property MARK_DEBUG true [get_nets fifo_full]
set_property MARK_DEBUG true [get_nets fifo_rd_en]
set_property MARK_DEBUG true [get_nets fifo_rd_valid]
set_property MARK_DEBUG true [get_nets fifo_rst]
set_property MARK_DEBUG true [get_nets fifo_wr_ack]
set_property MARK_DEBUG true [get_nets fifo_wr_en]
set_property MARK_DEBUG true [get_nets metric_counters_rst]
set_property MARK_DEBUG true [get_nets neorv32_pc_we]
set_property MARK_DEBUG true [get_nets neorv32_reset]
set_property MARK_DEBUG true [get_nets neorv32_run_counter_en]
set_property MARK_DEBUG true [get_nets start_debounced]
set_property MARK_DEBUG true [get_nets SNN_class_one]
set_property MARK_DEBUG true [get_nets SNN_class_one_pulse]
set_property MARK_DEBUG true [get_nets SNN_class_zero]
set_property MARK_DEBUG true [get_nets SNN_class_zero_pulse]
set_property MARK_DEBUG true [get_nets SNN_done]
set_property MARK_DEBUG true [get_nets start_i_IBUF]
set_property MARK_DEBUG true [get_nets start_pulse]
set_property MARK_DEBUG true [get_nets watchdog_error]
set_property MARK_DEBUG true [get_nets watchdog_ready]
set_property MARK_DEBUG true [get_nets watchdog_rst]
set_property MARK_DEBUG true [get_nets watchdog_rst_n]
set_property MARK_DEBUG true [get_nets {Bit_1_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_1_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_2_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_2_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_3_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_3_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_4_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_4_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_5_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_5_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_6_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_6_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_7_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_7_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_8_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_8_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_9_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_9_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {Bit_10_Fault_Controller_inst/Current_State[0]}]
set_property MARK_DEBUG true [get_nets {Bit_10_Fault_Controller_inst/Current_State[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/features[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/S_Current_State[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/S_Current_State[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/S_Current_State[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/S_Current_State[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/SNN_classes[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/SNN_classes[1]}]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/SNN_done]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/SNN_ready]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/SNN_trigger]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/instruction_executed]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/FL_ffs_rst]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/FL_output_ffs_wr]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/data_sample_reg[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[19]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[16]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[17]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[18]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_layer_spikes[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_layer_spikes[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[3]}]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/class_0_winner]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/class_1_winner]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/data_sample_reg_en]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/hidden_layer_ready]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes_ready]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/output_layer_ready]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/output_layer_trigger]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/SNN_done]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/SNN_ready]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/hidden_layer_inst/neuron_membrane_reg_wr]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/hidden_layer_inst/neuron_spike_ffs_wr]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/output_layer_inst/layer_spikes_reg_en]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/output_layer_inst/output_layer_spikes_ready]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/fast_SNN_inst/output_layer_inst/neuron_spike_ffs_wr]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[20]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[25]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[16]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[20]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[30]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[27]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[17]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[21]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[26]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[17]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[18]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[24]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[29]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[31]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[22]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[29]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[23]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[19]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[24]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[19]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[18]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[30]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[26]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[28]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[22]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[28]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[25]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_ir[27]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[16]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[21]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[23]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/current_pc[31]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/execute_states_data[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/execute_states_data[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/execute_states_data[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/execute_states_data[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[20]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[26]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[27]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[29]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[30]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[17]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[18]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[21]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[22]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[23]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[25]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[16]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[19]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[24]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[28]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir[31]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[0]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[6]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[17]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[21]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[22]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[30]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[18]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[3]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[5]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[8]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[14]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[16]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[19]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[25]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[31]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[27]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[2]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[9]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[11]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[13]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[20]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[23]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[29]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[7]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[1]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[4]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[10]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[12]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[15]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[24]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[26]}]
set_property MARK_DEBUG true [get_nets {watchdog_2_inst/feature_layer_2_inst/last_pc[28]}]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/cpu_branched_state]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/branch_valid]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/cpu_trap_exit_state]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/cpu_trap_enter_state]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/jal_valid]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/jalr_valid]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/pc_increment]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/trap_enter_valid]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/neorv32_booted_up]
set_property MARK_DEBUG true [get_nets watchdog_2_inst/feature_layer_2_inst/trap_exit_valid]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_100mhz/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[0]} {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[1]} {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[2]} {watchdog_2_inst/fast_SNN_inst/S_SNN_Current_State[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {Bit_10_Fault_Controller_inst/Current_State[0]} {Bit_10_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {Bit_9_Fault_Controller_inst/Current_State[0]} {Bit_9_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {Bit_4_Fault_Controller_inst/Current_State[0]} {Bit_4_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {Bit_6_Fault_Controller_inst/Current_State[0]} {Bit_6_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {Bit_7_Fault_Controller_inst/Current_State[0]} {Bit_7_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {Bit_8_Fault_Controller_inst/Current_State[0]} {Bit_8_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {Bit_2_Fault_Controller_inst/Current_State[0]} {Bit_2_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 2 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {Bit_3_Fault_Controller_inst/Current_State[0]} {Bit_3_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 2 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {Bit_5_Fault_Controller_inst/Current_State[0]} {Bit_5_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {Bit_1_Fault_Controller_inst/Current_State[0]} {Bit_1_Fault_Controller_inst/Current_State[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {total_classes_counter[0]} {total_classes_counter[1]} {total_classes_counter[2]} {total_classes_counter[3]} {total_classes_counter[4]} {total_classes_counter[5]} {total_classes_counter[6]} {total_classes_counter[7]} {total_classes_counter[8]} {total_classes_counter[9]} {total_classes_counter[10]} {total_classes_counter[11]} {total_classes_counter[12]} {total_classes_counter[13]} {total_classes_counter[14]} {total_classes_counter[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 16 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {total_label_1_classes_counter[0]} {total_label_1_classes_counter[1]} {total_label_1_classes_counter[2]} {total_label_1_classes_counter[3]} {total_label_1_classes_counter[4]} {total_label_1_classes_counter[5]} {total_label_1_classes_counter[6]} {total_label_1_classes_counter[7]} {total_label_1_classes_counter[8]} {total_label_1_classes_counter[9]} {total_label_1_classes_counter[10]} {total_label_1_classes_counter[11]} {total_label_1_classes_counter[12]} {total_label_1_classes_counter[13]} {total_label_1_classes_counter[14]} {total_label_1_classes_counter[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 32 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {neorv32_run_counter[0]} {neorv32_run_counter[1]} {neorv32_run_counter[2]} {neorv32_run_counter[3]} {neorv32_run_counter[4]} {neorv32_run_counter[5]} {neorv32_run_counter[6]} {neorv32_run_counter[7]} {neorv32_run_counter[8]} {neorv32_run_counter[9]} {neorv32_run_counter[10]} {neorv32_run_counter[11]} {neorv32_run_counter[12]} {neorv32_run_counter[13]} {neorv32_run_counter[14]} {neorv32_run_counter[15]} {neorv32_run_counter[16]} {neorv32_run_counter[17]} {neorv32_run_counter[18]} {neorv32_run_counter[19]} {neorv32_run_counter[20]} {neorv32_run_counter[21]} {neorv32_run_counter[22]} {neorv32_run_counter[23]} {neorv32_run_counter[24]} {neorv32_run_counter[25]} {neorv32_run_counter[26]} {neorv32_run_counter[27]} {neorv32_run_counter[28]} {neorv32_run_counter[29]} {neorv32_run_counter[30]} {neorv32_run_counter[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 16 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {total_label_0_classes_counter[0]} {total_label_0_classes_counter[1]} {total_label_0_classes_counter[2]} {total_label_0_classes_counter[3]} {total_label_0_classes_counter[4]} {total_label_0_classes_counter[5]} {total_label_0_classes_counter[6]} {total_label_0_classes_counter[7]} {total_label_0_classes_counter[8]} {total_label_0_classes_counter[9]} {total_label_0_classes_counter[10]} {total_label_0_classes_counter[11]} {total_label_0_classes_counter[12]} {total_label_0_classes_counter[13]} {total_label_0_classes_counter[14]} {total_label_0_classes_counter[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {watchdog_2_inst/feature_layer_2_inst/current_ir[0]} {watchdog_2_inst/feature_layer_2_inst/current_ir[1]} {watchdog_2_inst/feature_layer_2_inst/current_ir[2]} {watchdog_2_inst/feature_layer_2_inst/current_ir[3]} {watchdog_2_inst/feature_layer_2_inst/current_ir[4]} {watchdog_2_inst/feature_layer_2_inst/current_ir[5]} {watchdog_2_inst/feature_layer_2_inst/current_ir[6]} {watchdog_2_inst/feature_layer_2_inst/current_ir[7]} {watchdog_2_inst/feature_layer_2_inst/current_ir[8]} {watchdog_2_inst/feature_layer_2_inst/current_ir[9]} {watchdog_2_inst/feature_layer_2_inst/current_ir[10]} {watchdog_2_inst/feature_layer_2_inst/current_ir[11]} {watchdog_2_inst/feature_layer_2_inst/current_ir[12]} {watchdog_2_inst/feature_layer_2_inst/current_ir[13]} {watchdog_2_inst/feature_layer_2_inst/current_ir[14]} {watchdog_2_inst/feature_layer_2_inst/current_ir[15]} {watchdog_2_inst/feature_layer_2_inst/current_ir[16]} {watchdog_2_inst/feature_layer_2_inst/current_ir[17]} {watchdog_2_inst/feature_layer_2_inst/current_ir[18]} {watchdog_2_inst/feature_layer_2_inst/current_ir[19]} {watchdog_2_inst/feature_layer_2_inst/current_ir[20]} {watchdog_2_inst/feature_layer_2_inst/current_ir[21]} {watchdog_2_inst/feature_layer_2_inst/current_ir[22]} {watchdog_2_inst/feature_layer_2_inst/current_ir[23]} {watchdog_2_inst/feature_layer_2_inst/current_ir[24]} {watchdog_2_inst/feature_layer_2_inst/current_ir[25]} {watchdog_2_inst/feature_layer_2_inst/current_ir[26]} {watchdog_2_inst/feature_layer_2_inst/current_ir[27]} {watchdog_2_inst/feature_layer_2_inst/current_ir[28]} {watchdog_2_inst/feature_layer_2_inst/current_ir[29]} {watchdog_2_inst/feature_layer_2_inst/current_ir[30]} {watchdog_2_inst/feature_layer_2_inst/current_ir[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {watchdog_2_inst/feature_layer_2_inst/last_ir[0]} {watchdog_2_inst/feature_layer_2_inst/last_ir[1]} {watchdog_2_inst/feature_layer_2_inst/last_ir[2]} {watchdog_2_inst/feature_layer_2_inst/last_ir[3]} {watchdog_2_inst/feature_layer_2_inst/last_ir[4]} {watchdog_2_inst/feature_layer_2_inst/last_ir[5]} {watchdog_2_inst/feature_layer_2_inst/last_ir[6]} {watchdog_2_inst/feature_layer_2_inst/last_ir[7]} {watchdog_2_inst/feature_layer_2_inst/last_ir[8]} {watchdog_2_inst/feature_layer_2_inst/last_ir[9]} {watchdog_2_inst/feature_layer_2_inst/last_ir[10]} {watchdog_2_inst/feature_layer_2_inst/last_ir[11]} {watchdog_2_inst/feature_layer_2_inst/last_ir[12]} {watchdog_2_inst/feature_layer_2_inst/last_ir[13]} {watchdog_2_inst/feature_layer_2_inst/last_ir[14]} {watchdog_2_inst/feature_layer_2_inst/last_ir[15]} {watchdog_2_inst/feature_layer_2_inst/last_ir[16]} {watchdog_2_inst/feature_layer_2_inst/last_ir[17]} {watchdog_2_inst/feature_layer_2_inst/last_ir[18]} {watchdog_2_inst/feature_layer_2_inst/last_ir[19]} {watchdog_2_inst/feature_layer_2_inst/last_ir[20]} {watchdog_2_inst/feature_layer_2_inst/last_ir[21]} {watchdog_2_inst/feature_layer_2_inst/last_ir[22]} {watchdog_2_inst/feature_layer_2_inst/last_ir[23]} {watchdog_2_inst/feature_layer_2_inst/last_ir[24]} {watchdog_2_inst/feature_layer_2_inst/last_ir[25]} {watchdog_2_inst/feature_layer_2_inst/last_ir[26]} {watchdog_2_inst/feature_layer_2_inst/last_ir[27]} {watchdog_2_inst/feature_layer_2_inst/last_ir[28]} {watchdog_2_inst/feature_layer_2_inst/last_ir[29]} {watchdog_2_inst/feature_layer_2_inst/last_ir[30]} {watchdog_2_inst/feature_layer_2_inst/last_ir[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 2 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {watchdog_2_inst/SNN_classes[0]} {watchdog_2_inst/SNN_classes[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 4 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[0]} {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[1]} {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[2]} {watchdog_2_inst/fast_SNN_inst/output_neuron_0_spike_counter_reg[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 4 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[0]} {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[1]} {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[2]} {watchdog_2_inst/fast_SNN_inst/timestep_counter_reg[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 2 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {watchdog_2_inst/fast_SNN_inst/output_layer_spikes[0]} {watchdog_2_inst/fast_SNN_inst/output_layer_spikes[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 16 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {watchdog_2_inst/fast_SNN_inst/data_sample_reg[0]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[1]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[2]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[3]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[4]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[5]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[6]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[7]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[8]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[9]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[10]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[11]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[12]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[13]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[14]} {watchdog_2_inst/fast_SNN_inst/data_sample_reg[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 16 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[0]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[1]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[2]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[3]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[4]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[5]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[6]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[7]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[8]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[9]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[10]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[11]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[12]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[13]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[14]} {watchdog_2_inst/fast_SNN_inst/input_layer_spikes[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 4 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {watchdog_2_inst/feature_layer_2_inst/execute_states_data[0]} {watchdog_2_inst/feature_layer_2_inst/execute_states_data[1]} {watchdog_2_inst/feature_layer_2_inst/execute_states_data[2]} {watchdog_2_inst/feature_layer_2_inst/execute_states_data[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 7 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[0]} {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[1]} {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[2]} {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[3]} {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[4]} {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[5]} {watchdog_2_inst/feature_layer_2_inst/last_ir_opcode[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 32 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {watchdog_2_inst/feature_layer_2_inst/current_pc[0]} {watchdog_2_inst/feature_layer_2_inst/current_pc[1]} {watchdog_2_inst/feature_layer_2_inst/current_pc[2]} {watchdog_2_inst/feature_layer_2_inst/current_pc[3]} {watchdog_2_inst/feature_layer_2_inst/current_pc[4]} {watchdog_2_inst/feature_layer_2_inst/current_pc[5]} {watchdog_2_inst/feature_layer_2_inst/current_pc[6]} {watchdog_2_inst/feature_layer_2_inst/current_pc[7]} {watchdog_2_inst/feature_layer_2_inst/current_pc[8]} {watchdog_2_inst/feature_layer_2_inst/current_pc[9]} {watchdog_2_inst/feature_layer_2_inst/current_pc[10]} {watchdog_2_inst/feature_layer_2_inst/current_pc[11]} {watchdog_2_inst/feature_layer_2_inst/current_pc[12]} {watchdog_2_inst/feature_layer_2_inst/current_pc[13]} {watchdog_2_inst/feature_layer_2_inst/current_pc[14]} {watchdog_2_inst/feature_layer_2_inst/current_pc[15]} {watchdog_2_inst/feature_layer_2_inst/current_pc[16]} {watchdog_2_inst/feature_layer_2_inst/current_pc[17]} {watchdog_2_inst/feature_layer_2_inst/current_pc[18]} {watchdog_2_inst/feature_layer_2_inst/current_pc[19]} {watchdog_2_inst/feature_layer_2_inst/current_pc[20]} {watchdog_2_inst/feature_layer_2_inst/current_pc[21]} {watchdog_2_inst/feature_layer_2_inst/current_pc[22]} {watchdog_2_inst/feature_layer_2_inst/current_pc[23]} {watchdog_2_inst/feature_layer_2_inst/current_pc[24]} {watchdog_2_inst/feature_layer_2_inst/current_pc[25]} {watchdog_2_inst/feature_layer_2_inst/current_pc[26]} {watchdog_2_inst/feature_layer_2_inst/current_pc[27]} {watchdog_2_inst/feature_layer_2_inst/current_pc[28]} {watchdog_2_inst/feature_layer_2_inst/current_pc[29]} {watchdog_2_inst/feature_layer_2_inst/current_pc[30]} {watchdog_2_inst/feature_layer_2_inst/current_pc[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 4 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[0]} {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[1]} {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[2]} {watchdog_2_inst/fast_SNN_inst/output_neuron_1_spike_counter_reg[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 32 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {watchdog_2_inst/feature_layer_2_inst/last_pc[0]} {watchdog_2_inst/feature_layer_2_inst/last_pc[1]} {watchdog_2_inst/feature_layer_2_inst/last_pc[2]} {watchdog_2_inst/feature_layer_2_inst/last_pc[3]} {watchdog_2_inst/feature_layer_2_inst/last_pc[4]} {watchdog_2_inst/feature_layer_2_inst/last_pc[5]} {watchdog_2_inst/feature_layer_2_inst/last_pc[6]} {watchdog_2_inst/feature_layer_2_inst/last_pc[7]} {watchdog_2_inst/feature_layer_2_inst/last_pc[8]} {watchdog_2_inst/feature_layer_2_inst/last_pc[9]} {watchdog_2_inst/feature_layer_2_inst/last_pc[10]} {watchdog_2_inst/feature_layer_2_inst/last_pc[11]} {watchdog_2_inst/feature_layer_2_inst/last_pc[12]} {watchdog_2_inst/feature_layer_2_inst/last_pc[13]} {watchdog_2_inst/feature_layer_2_inst/last_pc[14]} {watchdog_2_inst/feature_layer_2_inst/last_pc[15]} {watchdog_2_inst/feature_layer_2_inst/last_pc[16]} {watchdog_2_inst/feature_layer_2_inst/last_pc[17]} {watchdog_2_inst/feature_layer_2_inst/last_pc[18]} {watchdog_2_inst/feature_layer_2_inst/last_pc[19]} {watchdog_2_inst/feature_layer_2_inst/last_pc[20]} {watchdog_2_inst/feature_layer_2_inst/last_pc[21]} {watchdog_2_inst/feature_layer_2_inst/last_pc[22]} {watchdog_2_inst/feature_layer_2_inst/last_pc[23]} {watchdog_2_inst/feature_layer_2_inst/last_pc[24]} {watchdog_2_inst/feature_layer_2_inst/last_pc[25]} {watchdog_2_inst/feature_layer_2_inst/last_pc[26]} {watchdog_2_inst/feature_layer_2_inst/last_pc[27]} {watchdog_2_inst/feature_layer_2_inst/last_pc[28]} {watchdog_2_inst/feature_layer_2_inst/last_pc[29]} {watchdog_2_inst/feature_layer_2_inst/last_pc[30]} {watchdog_2_inst/feature_layer_2_inst/last_pc[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 20 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[0]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[1]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[2]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[3]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[4]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[5]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[6]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[7]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[8]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[9]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[10]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[11]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[12]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[13]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[14]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[15]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[16]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[17]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[18]} {watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes[19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 4 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {watchdog_2_inst/S_Current_State[0]} {watchdog_2_inst/S_Current_State[1]} {watchdog_2_inst/S_Current_State[2]} {watchdog_2_inst/S_Current_State[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 16 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {watchdog_2_inst/features[0]} {watchdog_2_inst/features[1]} {watchdog_2_inst/features[2]} {watchdog_2_inst/features[3]} {watchdog_2_inst/features[4]} {watchdog_2_inst/features[5]} {watchdog_2_inst/features[6]} {watchdog_2_inst/features[7]} {watchdog_2_inst/features[8]} {watchdog_2_inst/features[9]} {watchdog_2_inst/features[10]} {watchdog_2_inst/features[11]} {watchdog_2_inst/features[12]} {watchdog_2_inst/features[13]} {watchdog_2_inst/features[14]} {watchdog_2_inst/features[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 20 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {FIL_four_to_one_mux_selects[1]} {FIL_four_to_one_mux_selects[2]} {FIL_four_to_one_mux_selects[3]} {FIL_four_to_one_mux_selects[4]} {FIL_four_to_one_mux_selects[5]} {FIL_four_to_one_mux_selects[6]} {FIL_four_to_one_mux_selects[7]} {FIL_four_to_one_mux_selects[8]} {FIL_four_to_one_mux_selects[9]} {FIL_four_to_one_mux_selects[10]} {FIL_four_to_one_mux_selects[11]} {FIL_four_to_one_mux_selects[12]} {FIL_four_to_one_mux_selects[13]} {FIL_four_to_one_mux_selects[14]} {FIL_four_to_one_mux_selects[15]} {FIL_four_to_one_mux_selects[16]} {FIL_four_to_one_mux_selects[17]} {FIL_four_to_one_mux_selects[18]} {FIL_four_to_one_mux_selects[19]} {FIL_four_to_one_mux_selects[20]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 4 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {S_top_Current_State[0]} {S_top_Current_State[1]} {S_top_Current_State[2]} {S_top_Current_State[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list bit_fault_inj_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list watchdog_2_inst/feature_layer_2_inst/branch_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list watchdog_2_inst/fast_SNN_inst/class_0_winner]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list watchdog_2_inst/fast_SNN_inst/class_1_winner]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list watchdog_2_inst/feature_layer_2_inst/cpu_branched_state]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list watchdog_2_inst/feature_layer_2_inst/cpu_trap_enter_state]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list watchdog_2_inst/feature_layer_2_inst/cpu_trap_exit_state]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list watchdog_2_inst/fast_SNN_inst/data_sample_reg_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list fault_injection_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list fifo_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list fifo_error]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list fifo_rd_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list fifo_rd_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list fifo_rst]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list fifo_wr_ack]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list fifo_wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list watchdog_2_inst/FL_ffs_rst]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list watchdog_2_inst/FL_output_ffs_wr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list watchdog_2_inst/fast_SNN_inst/hidden_layer_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
connect_debug_port u_ila_0/probe53 [get_nets [list watchdog_2_inst/fast_SNN_inst/hidden_layer_spikes_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
connect_debug_port u_ila_0/probe54 [get_nets [list watchdog_2_inst/instruction_executed]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
connect_debug_port u_ila_0/probe55 [get_nets [list watchdog_2_inst/feature_layer_2_inst/jal_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
connect_debug_port u_ila_0/probe56 [get_nets [list watchdog_2_inst/feature_layer_2_inst/jalr_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
connect_debug_port u_ila_0/probe57 [get_nets [list watchdog_2_inst/fast_SNN_inst/output_layer_inst/layer_spikes_reg_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
connect_debug_port u_ila_0/probe58 [get_nets [list metric_counters_rst]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
connect_debug_port u_ila_0/probe59 [get_nets [list watchdog_2_inst/feature_layer_2_inst/neorv32_booted_up]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
connect_debug_port u_ila_0/probe60 [get_nets [list neorv32_pc_we]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
connect_debug_port u_ila_0/probe61 [get_nets [list neorv32_reset]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
connect_debug_port u_ila_0/probe62 [get_nets [list neorv32_run_counter_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
connect_debug_port u_ila_0/probe63 [get_nets [list watchdog_2_inst/fast_SNN_inst/hidden_layer_inst/neuron_membrane_reg_wr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
connect_debug_port u_ila_0/probe64 [get_nets [list watchdog_2_inst/fast_SNN_inst/hidden_layer_inst/neuron_spike_ffs_wr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe65]
set_property port_width 1 [get_debug_ports u_ila_0/probe65]
connect_debug_port u_ila_0/probe65 [get_nets [list watchdog_2_inst/fast_SNN_inst/output_layer_inst/neuron_spike_ffs_wr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe66]
set_property port_width 1 [get_debug_ports u_ila_0/probe66]
connect_debug_port u_ila_0/probe66 [get_nets [list watchdog_2_inst/fast_SNN_inst/output_layer_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe67]
set_property port_width 1 [get_debug_ports u_ila_0/probe67]
connect_debug_port u_ila_0/probe67 [get_nets [list watchdog_2_inst/fast_SNN_inst/output_layer_inst/output_layer_spikes_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe68]
set_property port_width 1 [get_debug_ports u_ila_0/probe68]
connect_debug_port u_ila_0/probe68 [get_nets [list watchdog_2_inst/fast_SNN_inst/output_layer_trigger]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe69]
set_property port_width 1 [get_debug_ports u_ila_0/probe69]
connect_debug_port u_ila_0/probe69 [get_nets [list watchdog_2_inst/feature_layer_2_inst/pc_increment]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe70]
set_property port_width 1 [get_debug_ports u_ila_0/probe70]
connect_debug_port u_ila_0/probe70 [get_nets [list SNN_class_one]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe71]
set_property port_width 1 [get_debug_ports u_ila_0/probe71]
connect_debug_port u_ila_0/probe71 [get_nets [list SNN_class_one_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe72]
set_property port_width 1 [get_debug_ports u_ila_0/probe72]
connect_debug_port u_ila_0/probe72 [get_nets [list SNN_class_zero]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe73]
set_property port_width 1 [get_debug_ports u_ila_0/probe73]
connect_debug_port u_ila_0/probe73 [get_nets [list SNN_class_zero_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe74]
set_property port_width 1 [get_debug_ports u_ila_0/probe74]
connect_debug_port u_ila_0/probe74 [get_nets [list watchdog_2_inst/fast_SNN_inst/SNN_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe75]
set_property port_width 1 [get_debug_ports u_ila_0/probe75]
connect_debug_port u_ila_0/probe75 [get_nets [list watchdog_2_inst/SNN_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe76]
set_property port_width 1 [get_debug_ports u_ila_0/probe76]
connect_debug_port u_ila_0/probe76 [get_nets [list SNN_done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe77]
set_property port_width 1 [get_debug_ports u_ila_0/probe77]
connect_debug_port u_ila_0/probe77 [get_nets [list watchdog_2_inst/fast_SNN_inst/SNN_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe78]
set_property port_width 1 [get_debug_ports u_ila_0/probe78]
connect_debug_port u_ila_0/probe78 [get_nets [list watchdog_2_inst/SNN_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe79]
set_property port_width 1 [get_debug_ports u_ila_0/probe79]
connect_debug_port u_ila_0/probe79 [get_nets [list watchdog_2_inst/SNN_trigger]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe80]
set_property port_width 1 [get_debug_ports u_ila_0/probe80]
connect_debug_port u_ila_0/probe80 [get_nets [list start_debounced]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe81]
set_property port_width 1 [get_debug_ports u_ila_0/probe81]
connect_debug_port u_ila_0/probe81 [get_nets [list start_i_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe82]
set_property port_width 1 [get_debug_ports u_ila_0/probe82]
connect_debug_port u_ila_0/probe82 [get_nets [list start_pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe83]
set_property port_width 1 [get_debug_ports u_ila_0/probe83]
connect_debug_port u_ila_0/probe83 [get_nets [list watchdog_2_inst/feature_layer_2_inst/trap_enter_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe84]
set_property port_width 1 [get_debug_ports u_ila_0/probe84]
connect_debug_port u_ila_0/probe84 [get_nets [list watchdog_2_inst/feature_layer_2_inst/trap_exit_valid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe85]
set_property port_width 1 [get_debug_ports u_ila_0/probe85]
connect_debug_port u_ila_0/probe85 [get_nets [list watchdog_error]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe86]
set_property port_width 1 [get_debug_ports u_ila_0/probe86]
connect_debug_port u_ila_0/probe86 [get_nets [list watchdog_ready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe87]
set_property port_width 1 [get_debug_ports u_ila_0/probe87]
connect_debug_port u_ila_0/probe87 [get_nets [list watchdog_rst]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe88]
set_property port_width 1 [get_debug_ports u_ila_0/probe88]
connect_debug_port u_ila_0/probe88 [get_nets [list watchdog_rst_n]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100MHz]
